/* #############
# add columns for caching
############# */
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_calced_path VARCHAR(255) GENERATED ALWAYS AS (LOWER(CONCAT(i_dir, "/", i_file))) STORED;
CREATE INDEX IF NOT EXISTS idx_I__I_CALCED_PATH ON image (i_calced_path);
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_calced_path2 VARCHAR(255) GENERATED ALWAYS AS (LOWER(CONCAT(i_dir, "_", i_file))) STORED;
CREATE INDEX IF NOT EXISTS idx_I__I_CALCED_PATH2 ON image (i_calced_path2);
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_calced_file VARCHAR(255) GENERATED ALWAYS AS (LOWER(i_file)) STORED;
CREATE INDEX IF NOT EXISTS idx_I__I_CALCED_FILE ON image (i_calced_file);
CREATE INDEX IF NOT EXISTS idx_I__I_FILE ON image (I_FILE);

ALTER TABLE video ADD COLUMN IF NOT EXISTS v_calced_path VARCHAR(255) GENERATED ALWAYS AS (LOWER(CONCAT(v_dir, "/", v_file))) STORED;
CREATE INDEX IF NOT EXISTS idx_V__V_CALCED_PATH ON video (v_calced_path);
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_calced_path2 VARCHAR(255) GENERATED ALWAYS AS (LOWER(CONCAT(v_dir, "_", v_file))) STORED;
CREATE INDEX IF NOT EXISTS idx_V__V_CALCED_PATH2 ON video (v_calced_path2);
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_calced_file VARCHAR(255) GENERATED ALWAYS AS (LOWER(v_file)) STORED;
CREATE INDEX IF NOT EXISTS idx_V__V_CALCED_FILE ON video (v_calced_file);
CREATE INDEX IF NOT EXISTS idx_V__V_FILE ON video (V_FILE);
