-- ----------------
-- add mediameta-fields
-- ----------------
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_datefile DATETIME DEFAULT NULL;
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_daterecording DATETIME DEFAULT NULL;
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_filesize INT(11) DEFAULT NULL;
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_metadata TEXT DEFAULT NULL;
ALTER TABLE image ADD COLUMN IF NOT EXISTS i_resolution VARCHAR(50) DEFAULT NULL;

ALTER TABLE video ADD COLUMN IF NOT EXISTS v_datefile DATETIME DEFAULT NULL;
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_daterecording DATETIME DEFAULT NULL;
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_duration INT(11) DEFAULT NULL;
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_filesize INT(11) DEFAULT NULL;
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_metadata TEXT DEFAULT NULL;
ALTER TABLE video ADD COLUMN IF NOT EXISTS v_resolution VARCHAR(50) DEFAULT NULL;
