-- ----------------
-- add mediameta-fields
-- ----------------
ALTER TABLE image ADD COLUMN i_datefile DATETIME DEFAULT NULL;
ALTER TABLE image ADD COLUMN i_daterecording DATETIME DEFAULT NULL;
ALTER TABLE image ADD COLUMN i_filesize INT(11) DEFAULT NULL;
ALTER TABLE image ADD COLUMN i_metadata TEXT DEFAULT NULL;
ALTER TABLE image ADD COLUMN i_resolution VARCHAR(50) DEFAULT NULL;

ALTER TABLE video ADD COLUMN v_datefile DATETIME DEFAULT NULL;
ALTER TABLE video ADD COLUMN v_daterecording DATETIME DEFAULT NULL;
ALTER TABLE video ADD COLUMN v_duration INT(11) DEFAULT NULL;
ALTER TABLE video ADD COLUMN v_filesize INT(11) DEFAULT NULL;
ALTER TABLE video ADD COLUMN v_metadata TEXT DEFAULT NULL;
ALTER TABLE video ADD COLUMN v_resolution VARCHAR(50) DEFAULT NULL;
