-- ----------------
-- add pdffile-fields
-- ----------------
ALTER TABLE kategorie ADD COLUMN k_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE image ADD COLUMN i_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE info ADD COLUMN if_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE location ADD COLUMN l_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE news ADD COLUMN n_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE poi ADD COLUMN poi_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE tour ADD COLUMN t_pdffile VARCHAR(250) DEFAULT NULL;
ALTER TABLE trip ADD COLUMN tr_pdffile VARCHAR(250) DEFAULT NULL;
