version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  solr:
    build: ./solr
    ports:
      - "8983:8983"
    depends_on:
      - mysqldb
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    links:
      - "mysqldb:mysqldb"
    networks:
      - prodnetwork
  mysqldb:
    build: ./mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlRoot
      - MYSQL_ROOT_HOST=192.168.99.1
      - MYSQL_DATABASE=matweb
      - MYSQL_USER=matweb
      - MYSQL_PASSWORD=
    networks:
      - prodnetwork
